#-Dserver.port=8081
spring:
  redis:
    host: 192.168.13.171
    port: 6379
    database: 15
    password: iampassword
    timeout: 5000
    lettuce:
      pool:
        max-active: 2000 #连接池最大连接数（使用负值表示没有限制）默认8
        max-idle: 8  #连接池中的最大空闲连接 默认 8
        min-idle: 1  #连接池中的最小空闲连接 默认 0
        max-wait: 5000