server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    #binlogName: binlog.000038
    #position: 60451